### ISSUE TITLE
添加 filter 与 备用 RSS 源

### ISSUE THREAD

**Issue by RetiredWorld** [mashirozx/tweet2toot#2]
添加了一个 filter 功能，添加原因为有些老师会在 twitter上发布作品，这些作品都有固定的格式（比如 title），可以通过这个来过滤只转嘟这些作品，而避开一些无关的内容。

```ini
[MASTODON]
Filter = None
```

添加方式为通过简单的正则表达式（  [re 模块](https://docs.python.org/3/library/re.html)）。如果选项设置为 None 则不使用过滤器。

**另外添加了一个备用 RSS 源的功能**：

```ini
[TWITTER]
TwitterRss = https://rss.zeka.cloud/twitter/user/ruanyf
BackupRss = https://rsshub.app/twitter/user/ruanyf
```
如果首要 rss 源头获取失败的话会自动转向备用源，这里我默认将首要源设置为了我自己的源（[rss.zeka.cloud](https://rss.zeka.cloud)）,因为我恰好申请到了开发者帐号，而且配额足够（应该），所以自作主张添加了自己的源，希望能缓解 RssHub 的压力。

我的 rsshub 是部署在 [Heroku](https://docs.rsshub.app/install/#bu-shu-dao-heroku) 的，并且设置了自动更新，好处是利于国内访问，我个人也用了一段时间了，没有出现问题。开发者帐号为小号，所以即使出了问题对我影响也不大。

上面的功能都向下兼容，所以更新后原配置不变不会有任何影响。

我的 版本在 [这里](https://github.com/RetiredWorld/tweet2toot)，如果你觉得我就提交 pr 力。
上面其实提供了两个功能，我的 pr 是 一起的，如果你只希望一个功能，我可以拆分。

**Comment by mashirozx** [comment]
ok哒，等你pr
